// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_C_fOl-xN9dwVXUO8Is_EyhdcvuayNOg',
    appId: '1:269604310634:android:9b856a3d44c9762e73c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6pPIrr4AIl_td_ODRVG8Cdc_F16dSnb0',
    appId: '1:269604310634:ios:6b64242350a6066673c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
    androidClientId: '269604310634-23tak25f2k6vamftfr11lmtadn0a211t.apps.googleusercontent.com',
    iosClientId: '269604310634-9rl2rn87msr0phqobo5bpusqdgm3ocio.apps.googleusercontent.com',
    iosBundleId: 'com.example.thanhhoaGardenStaffApp',
  );
}
